### ISSUE TITLE
Wondering if your JWT method can work in ExistDB 4.x with no coding changes.   

### ISSUE THREAD

**Issue by allanc007** [telic/exist-jwt#1]
Using ExistDB 4.3.
Used the included ANT script to build the package library.   

The following library appears in my ExistDB Package Manager as:      
JWT Parser / Verifier 0.1.1 

In the ExistDB (eXide) xquery editor; I don't see your single method appearing in the Outline view.   
Wondering if the code base needs to be updated to work in Exist 4.3 or greater.  
    
```
xquery version "3.1";
import module namespace jta = "http://max.terpstra.ca/ns/exist-jwt" 
                                              at "java:ca.terpstra.max.exist_jwt.JwtModule";

declare variable $local:InboundString as xs:string := '';  
declare variable $local:DATABASE as xs:string := 'local';

declare function local:callback ($inboundString as xs:string) as xs:string* 
{
    let $checkValue := $inboundString + '_madeit' 
    return $checkValue     
};

jwt:get-verified-claims('test', local:callback( ), 'audience' ) 

````
Would you be able to show me a sample implementation test case on how to use your function with a callback.  

Here is a quick hack above; that does not work for me at the moment.   
Seeing an error in the web editor saying:  

_Invalid qname jwt:get-verified-claims_

Appreciate any help you could share.      

Allan.

**Comment by telic** [comment]
This package was created for eXist 2.2; I have no idea whether the same extension format is still supported in 4.x. The fact that it shows up in the package manager is a good sign though.

That said, I see a few problems in your code snippet above. The error you're getting right now is because you've imported the module with the namespace "jta", but are trying to use it with "jwt". Also, the second parameter to `jwt:get-verified-claims` should be a function reference (you're calling the function directly and passing the resulting string). Lastly, your callback function should return zero or more JSON-Web-Keys encoded as JSON strings.

Using the library should look something like this:
```
import module namespace jwt = "http://max.terpstra.ca/ns/exist-jwt";
declare variable $token as xs:string external;
declare function local:key-callback($issuer as xs:string?) as xs:string* {
  (: do some work to find the appropriate keys, and eventually return something like :)
  '{"kid":"some key ID","alg":"HS512","k":"secretsecretsecret","kty":"oct","use":"sig"}'
};

let $claims := jwt:get-verified-claims($token, local:key-callback#1, 'expected-audience')
return <user-is>{ $claims('sub') }</user-is>
```
